apiVersion: v1
kind: Service
metadata:
  name: {{ include "dailyproof.fullname" . }}-web
  labels:
    {{- include "dailyproof.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "dailyproof.selectorLabels" (dict "Chart" .Chart "Release" .Release "component" "web") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
