---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dp-dailyproof-secret
  namespace: dailyproof
spec:
  encryptedData:
    SUPABASE_SERVICE_ROLE_KEY: AgBwK5iMBZ33wRHeS9WeusTZiMoFaFvOkWK9lReL6Wwi+ppabM88zq5Qpyc9QWF8PSVF1MldiO3SlDKFZ+5jTPJvngBzsa9FYeFCpPjfUYwip2Wwkf/NKbkp9uya7e2zz0pQ6+eWwllbnMQxdYLPGOpufhuuOIXPr+PubMuTLpdw0pOGj2/iz7ayUhUrXSlbk6eD8OLV6Z1RGD1iRD1+7pspD0yP1m6pjMPreJGvjIBEd7oxYJzFZty/bogK5fttA/PNwtM5JSv3EIQwSl/Ltnenfs7teGyFYuZI8dxis9ayG9P3LpOAacFUg23ArybLBfmOb8EmZKKOAP3lXsSENsAWe9Q0m9uKTVWAadU/3hfpl/eWYSpsIiQhZIZRTfDczTHT7H4yIUyNIRQu6t6eqU17sh9XPT8vhjMcBs26cczACHR/QZiSxiZjrpe9z/JUuMektR7JHWi+dvIjzrnnAJCMtPzQ2DvZH+DcWFvmkn59W1BsmkQpFfjPmeT+IA/YY4aPMyr5FwnNG0AU41d6zByakZR4oaf4n6i0/XOo2+OJo+rWTHda8EGzcKeVQ1lBqK5SEH+6JE5iqrwnEavWUooMCEsH6rbULcJph8K1Pp8pNkH2cscKcwuyRGh6dvB1YvM0FLUEq173QbDo7mGsyAX3J8w+ViuW+jaUiNXfp1M8wWIkUtCY8y6TTkLldE1KlwvtuWXyqAut5+LsLUDVHrpVGvQI6Rywfg4yQRICOCMUfscICRJJTYBj3FgQwd4MPFbnEfSjQnEfoNQhDi+7GJwcSw5RwaR+7Eci5uln++f73EIOqQHYL+fWXpAZz2dxB2YQyhdu54vFLG7QtPYBPQUeCieHSDw7I472R4SrbTw8tsXr7Tk/BdiP9LAGVAK51wGqsbPT7VSUDc9Z+FbJf3wMELPVybiwGxdfW3lctYMnZqrFAo/uXEOu9G+fFoiekNil95Lh5H55wwcLF1O/2pSyeWRhPDXo+bPIAAs=
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: dp
        meta.helm.sh/release-namespace: dailyproof
      labels:
        app.kubernetes.io/instance: dp
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: dailyproof
        app.kubernetes.io/version: 0.1.0
      name: dp-dailyproof-secret
      namespace: dailyproof
    type: Opaque
